version: '3.8'

services:
  blueghost:
    build: .
    container_name: blueghost_app
    ports:
      - "5000:5000"
    network_mode: "host"
    privileged: true
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
